/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydoituongdacbiet.view;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnChoosePrisoner = new javax.swing.JButton();
        btnChooseJail = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnChooseVisit = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Quản lý tình hình dân cư<br> ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 679));

        btnChoosePrisoner.setBackground(new java.awt.Color(0, 0, 102));
        btnChoosePrisoner.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChoosePrisoner.setForeground(new java.awt.Color(255, 255, 255));
        btnChoosePrisoner.setText("<html><div style='text-align: center;'>Quản lý Tù Nhân<br></div>");
        btnChoosePrisoner.setToolTipText("");
        btnChoosePrisoner.setActionCommand("<html><div style='text-align: center;'>Quản lý tù nhân<br></div>");
        btnChoosePrisoner.setBorder(null);
        btnChoosePrisoner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChoosePrisoner.setOpaque(true);
        btnChoosePrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePrisonerActionPerformed(evt);
            }
        });

        btnChooseJail.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseJail.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseJail.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseJail.setText("<html><div style='text-align: center;'>Quản lý Trại Giam<br></div>");
        btnChooseJail.setToolTipText("");
        btnChooseJail.setBorder(null);
        btnChooseJail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseJail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChooseJail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseJailActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("<html><div style='text-align: center;'>Quản lý Tù Nhân Trại Giam<br> ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setIcon(new ImageIcon(getClass().getResource("/images/Lovepik_com-500330964-blue-blazed-background.jpg")));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnChooseVisit.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseVisit.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseVisit.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseVisit.setText("<html><div style='text-align: center;'>Quản lý Thăm Nuôi<br></div>");
        btnChooseVisit.setToolTipText("");
        btnChooseVisit.setBorder(null);
        btnChooseVisit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseVisit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChooseVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseVisitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnChooseJail, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnChoosePrisoner, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btnChooseVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseJail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChoosePrisoner, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnChooseVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoosePrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePrisonerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoosePrisonerActionPerformed

    private void btnChooseJailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseJailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseJailActionPerformed

    private void btnChooseVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseVisitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void addChoosePrisonerListener(ActionListener listener){
        btnChoosePrisoner.addActionListener(listener);
    }
    
    public void addChooseJailListener(ActionListener listener){
        btnChooseJail.addActionListener(listener);
    }
    
    public void addChooseVisitListener(ActionListener listener){
        btnChooseVisit.addActionListener(listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseJail;
    private javax.swing.JButton btnChoosePrisoner;
    private javax.swing.JButton btnChooseVisit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
